# Generated by Django 3.0.2 on 2021-11-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('dept', models.CharField(choices=[('MF', 'Üretim'), ('SH', 'Nakliye'), ('AD', 'Yönetim'), ('HR', 'İnsan Kaynakları'), ('RD', 'Ar-Ge')], default='HR', max_length=2)),
            ],
        ),
    ]
